-- ============================================================
--  Rental agreement v2 — full attorney-drafted Roll Off Dumpster
--  Rental Agreement (12 sections), replacing the short v1 summary.
--  Confirms 14 cubic yard container to match the corrected site copy.
-- ============================================================

update agreement_templates set active = false
  where active = true and not exists (select 1 from agreement_templates where version = 2);

insert into agreement_templates (version, title, body_html, active)
select 2, 'Roll Off Dumpster Rental Agreement',
  $agreement_v2$
<h3>Roll Off Dumpster Rental Agreement</h3>
<p><strong>Texas Dumpster Company LLC</strong></p>
<p><strong>IMPORTANT TERMS.</strong> This Agreement governs delivery, rental, pickup, transportation, and disposal services. The customer should review the load limits, prohibited-material rules, access requirements, property-risk terms, and additional-charge authorization before accepting delivery.</p>
<p>Container: <strong>14 cubic yard roll off</strong>. Rental term, delivery date, pickup date, base price and included weight are as shown on your order confirmation.</p>
<p>Agreement formation. This Roll Off Dumpster Rental Agreement (Agreement) is between Texas Dumpster Company LLC (Company) and the person or entity identified in the order (Customer). The order confirmation, invoice, checkout page, delivery photographs, disposal ticket, and any written change approved by Company are incorporated into this Agreement. If they conflict, this Agreement controls unless the order confirmation expressly states otherwise.</p>
<h3>1 Rental Services and Term</h3>
<p>1.1 Company will deliver and retrieve the container identified in the order, subject to safe access, equipment availability, disposal-facility acceptance, law, and this Agreement. Dates and time windows are estimates, not guarantees, unless Company agrees otherwise in writing.</p>
<p>1.2 The rental begins when the container is delivered and ends when Company retrieves it. Customer must request pickup; the end of the selected rental period does not guarantee automatic removal unless the order expressly says so. Continued possession may incur the daily extension rate shown in the order or current price schedule.</p>
<p>1.3 The container remains Company property. Customer may not sell, sublease, conceal, alter, paint, deface, attach items to, move, tow, lift, or permit another hauler to service the container.</p>
<h3>2 Customer Authority and Site Conditions</h3>
<p>2.1 Customer represents that Customer owns the delivery location or has authority from the owner or authorized manager to order service and approve container placement.</p>
<p>2.2 Customer will select a level, firm, unobstructed location that can safely support the combined weight of the delivery vehicle, container, and contents. Customer will disclose known hazards, including septic systems, irrigation, utilities, soft ground, pavers, low branches, narrow gates, steep grades, overhead wires, and restricted access.</p>
<p>2.3 Customer authorizes Company to enter the property and position, adjust, or retrieve the container using reasonable judgment. Company may refuse or change placement when the requested location is unsafe, unlawful, inaccessible, or likely to damage equipment or property.</p>
<p>2.4 Heavy vehicles and containers can crack, rut, scratch, stain, or otherwise damage driveways, pavement, curbs, lawns, landscaping, and underground improvements even when reasonable care is used. Customer accepts those inherent placement and access risks. Boards or protective materials may reduce risk but do not guarantee prevention. This clause does not excuse damage caused by Company&#x27;s gross negligence or willful misconduct.</p>
<p>2.5 Customer must obtain any permit, right-of-way approval, parking authorization, HOA approval, or other consent required for placement. Customer is responsible for related fees, citations, towing costs, and penalties arising from Customer&#x27;s placement request or failure to obtain approval.</p>
<h3>3 Loading and Use Requirements</h3>
<p>3.1 Customer is responsible for the container and all contents from delivery until retrieval and disposal acceptance, including use by household members, contractors, invitees, trespassers, or others.</p>
<p>3.2 Material must be distributed evenly. Nothing may extend above the top rail or protrude from the sides, rear, or doors. The rear door must close and latch fully, and Company&#x27;s tarp must roll over the load without obstruction. Customer must not load material after requesting pickup. If the container is overfilled, Customer must unload or rearrange the contents and make the load safe for lawful transport before Company will retrieve it.</p>
<p>3.3 Customer must not exceed the container&#x27;s legal or operational weight limit, the included tonnage stated in the order, or any material-specific limit communicated by Company. Dense material such as dirt, concrete, brick, rock, asphalt, tile, plaster, shingles, or sod requires advance written approval and may be limited to a partial container or a dedicated load.</p>
<p>3.4 Unless Company approves otherwise in writing, loading is by hand only. Customer may not use a skid steer, tractor, excavator, compactor, vehicle, crane, or other powered equipment to load, push, strike, or compact material in or against the container.</p>
<p>3.5 Customer will keep children and unauthorized persons away from the container; keep doors secured when not actively loading; and not climb on, enter, burn in, sleep in, or use the container for any purpose other than approved waste loading.</p>
<h3>4 Acceptable and Prohibited Materials</h3>
<p>4.1 Only ordinary household, commercial, or construction debris specifically accepted by Company and the designated disposal facility may be loaded. Acceptance varies by facility and waste stream. Customer must ask Company before loading any questionable item.</p>
<p>4.2 The following are prohibited unless Company gives written approval and identifies the applicable handling charge:</p>
<ul><li>Hazardous, toxic, radioactive, explosive, corrosive, infectious, or regulated waste; asbestos or suspected asbestos; medical waste, sharps, bodily fluids, or animal carcasses.</li><li>Liquids, wet paint, solvents, chemicals, pesticides, herbicides, fuels, oils, grease, propane or compressed-gas cylinders, batteries, and pressurized containers.</li><li>Hot ashes, burning or smoldering material, fireworks, ammunition, explosives, and materials capable of igniting or reacting.</li><li>Refrigerators, freezers, air conditioners, dehumidifiers, or other refrigerant-containing equipment unless certified evacuated and preapproved.</li><li>Tires, mattresses, box springs, appliances, electronics, railroad ties, stumps, dirt, concrete, brick, rock, asphalt, tile, plaster, shingles, and other special or dense materials unless specifically preapproved.</li></ul>
<p>4.3 Latex paint may be accepted only when fully dried or solidified and when allowed by the disposal facility. Empty containers must be free of liquids and residue to the extent required by the disposal facility.</p>
<p>4.4 If prohibited, undisclosed, or rejected material is found, Company may refuse pickup, remove and return the material, isolate the load, or arrange lawful handling. Customer will pay all resulting labor, transport, cleanup, testing, disposal, delay, regulatory, and third-party charges, plus any lawful administrative fee disclosed in the price schedule. Customer remains responsible for classifying and lawfully disposing of Customer&#x27;s waste.</p>
<h3>5 Pickup Access and Readiness</h3>
<p>5.1 On the scheduled pickup date, Customer must provide safe, unobstructed access for the truck and container. Vehicles, locked gates, low wires or branches, animals, snow, mud, equipment, and other obstructions must be cleared before arrival.</p>
<p>5.2 The load must comply with Section 3. If access is blocked or the container is overloaded, overfilled, unsafe, frozen in place, moved, or otherwise not ready, Company may decline service. A blocked or unsuccessful pickup is subject to a $125 dry-run fee. An overfilled container is subject to a $75 overfill-handling fee, and Customer must unload or rearrange the contents to make the load safe for lawful transport before pickup. A new pickup must be scheduled, and additional rental charges may apply.</p>
<p>5.3 Company may remove or refuse to transport any unsafe load. Customer is responsible for unloading or correcting the load at Customer&#x27;s expense. Customer may not enter or modify the container while Company is operating equipment.</p>
<h3>6 Price Payment and Additional Charges</h3>
<p>6.1 Customer will pay the base price, taxes, and fees shown in the order. Unless stated otherwise, the base price includes one delivery, one pickup, one disposal event, the stated rental period, stated service area, and included weight allowance.</p>
<p><strong>Additional Charge Schedule</strong></p>
<table style="width:100%;border-collapse:collapse;font-size:.9em;"><thead><tr><th style="text-align:left;border-bottom:1px solid #ccc;padding:4px;">Charge</th><th style="text-align:left;border-bottom:1px solid #ccc;padding:4px;">Amount</th><th style="text-align:left;border-bottom:1px solid #ccc;padding:4px;">Application</th></tr></thead><tbody>
<tr><td style="padding:4px;border-bottom:1px solid #eee;">Excess weight</td><td style="padding:4px;border-bottom:1px solid #eee;">$90 per ton</td><td style="padding:4px;border-bottom:1px solid #eee;">Prorated by actual weight over the included allowance. Heavy or dense materials are excluded and require advance approval and separate pricing.</td></tr>
<tr><td style="padding:4px;border-bottom:1px solid #eee;">Dry run or blocked pickup</td><td style="padding:4px;border-bottom:1px solid #eee;">$125</td><td style="padding:4px;border-bottom:1px solid #eee;">Charged per unsuccessful service attempt when delivery or pickup access is blocked or the container is not ready for safe service.</td></tr>
<tr><td style="padding:4px;border-bottom:1px solid #eee;">Overfill handling</td><td style="padding:4px;border-bottom:1px solid #eee;">$75</td><td style="padding:4px;border-bottom:1px solid #eee;">Charged when material is above the top rail or prevents safe tarping or transport. Customer must make the load transport safe before pickup.</td></tr>
</tbody></table>
<p>6.2 Additional charges may also include extra rental days; additional dumps or swaps; excess mileage or fuel surcharge; wait time; relocation; overloaded loads; special items; prohibited-material handling; cleanup; damage; citations; permits; and charges imposed by a disposal facility. Rates not listed above are those disclosed in the order or Company&#x27;s price schedule in effect when the charge is incurred.</p>
<p>6.3 Scale tickets or disposal-facility records control actual weight. Weather may increase the weight of absorbent contents. Customer is responsible for excess weight caused by rain, snow, ice, saturation, or third-party use. Customer may cover the container with a customer-supplied cover only if it is removed before service and does not damage or obstruct Company equipment.</p>
<p>6.4 Customer authorizes Company to charge the payment method on file for amounts due under this Agreement, including post-service charges supported by scale tickets, photographs, invoices, repair records, or third-party receipts. Company will provide an itemized receipt or invoice. This authorization does not waive any nonwaivable right to question or dispute an incorrect charge.</p>
<p>6.5 Past-due balances may accrue the lesser of 1.5 percent per month or the maximum lawful rate. Customer will reimburse reasonable collection costs and attorney&#x27;s fees to the extent allowed by law.</p>
<h3>7 Cancellations Delays and Service Changes</h3>
<p>7.1 Cancellation and rescheduling charges, if any, are those disclosed at checkout or in the order confirmation. After dispatch or attempted delivery, Company may charge a trip or dry-run fee. After delivery, the rental is considered used even if Customer places no material in the container.</p>
<p>7.2 Company is not liable for delay or inability to perform caused by unsafe conditions, traffic, weather, road closure, equipment failure, disposal-facility closure or rejection, governmental action, labor disruption, emergency, force majeure, or other conditions beyond reasonable control. Company will use reasonable efforts to reschedule affected service.</p>
<h3>8 Loss Damage and Cleanup</h3>
<p>8.1 Customer is responsible for loss of or damage to the container beyond ordinary wear while it is at the delivery location, including theft, vandalism, graffiti, fire, unauthorized movement, misuse, or damage caused by Customer or others. Customer will promptly report any incident.</p>
<p>8.2 Customer is responsible for cleaning debris or leakage caused by Customer&#x27;s loading, prohibited materials, or use of the container. Company is responsible for cleaning debris directly caused by Company&#x27;s negligent handling during delivery or retrieval.</p>
<p>8.3 To the extent permitted by law, each party will defend, indemnify, and hold the other harmless from third-party claims, losses, fines, and reasonable legal costs to the extent caused by that party&#x27;s negligence, willful misconduct, or breach of this Agreement. Customer&#x27;s obligation includes claims arising from the waste, site conditions not disclosed to Company, Customer&#x27;s placement instructions, and use of the container by Customer or others under Customer&#x27;s control.</p>
<h3>9 Limits of Liability</h3>
<p>9.1 Except for payment obligations, indemnity obligations, property damage, personal injury, gross negligence, willful misconduct, or liability that cannot legally be limited, neither party is liable to the other for indirect, incidental, special, exemplary, punitive, or consequential damages, including lost profit or lost opportunity.</p>
<p>9.2 For claims that may lawfully be limited, Company&#x27;s aggregate liability arising from the order will not exceed the amount Customer paid Company for that order. Customer must allow Company a reasonable opportunity to inspect and address any claimed damage before repairs are made, except for emergency measures needed to prevent further loss.</p>
<h3>10 Default and Termination</h3>
<p>10.1 Company may suspend service, retrieve the container, or terminate the rental if Customer fails to pay, violates this Agreement, creates an unsafe or unlawful condition, misrepresents the waste, or interferes with Company&#x27;s property or operations. Customer remains responsible for charges already incurred and reasonable costs of retrieval and lawful disposal.</p>
<p>10.2 If Company cannot retrieve its container, Customer grants Company and its agents reasonable access to the delivery location for retrieval, subject to applicable law. This does not authorize breach of the peace or unlawful entry.</p>
<h3>11 General Legal Terms</h3>
<p>11.1 Texas law governs this Agreement, without regard to conflict-of-law principles. Any court proceeding must be brought in a court of competent jurisdiction in Williamson County, Texas, unless applicable law requires another venue. Before filing suit, the parties will make a good-faith effort for at least 30 days to resolve the dispute through written notice and direct discussion. Either party may use a court with small-claims jurisdiction when eligible.</p>
<p>11.2 Notices may be sent to the physical address, email address, or phone number shown in the order. Operational notices by text or email are effective when sent; formal legal notices are effective as provided by applicable law.</p>
<p>11.3 Electronic records, checkbox acceptance, typed signatures, and electronic signatures may be used to form and evidence this Agreement. Customer consents to receive the Agreement, order documents, receipts, and service communications electronically.</p>
<p>11.4 This Agreement and the incorporated order documents are the entire agreement for the service and replace prior discussions concerning that order. Any amendment must be in writing and accepted by both parties. Customer may not assign the Agreement without Company&#x27;s written consent; Company may assign it in connection with a transfer of its business or assets.</p>
<p>11.5 If any provision is unenforceable, it will be enforced to the maximum lawful extent and the remaining provisions will continue. A delay or failure to enforce a provision is not a waiver. Provisions concerning payment, waste responsibility, damage, indemnity, liability, dispute resolution, and recordkeeping survive completion or termination.</p>
<h3>12 Customer Acknowledgments</h3>
<p>By signing or electronically accepting, Customer confirms that Customer: (1) reviewed the order and this Agreement; (2) understands the included rental period and weight allowance; (3) accepts responsibility for site access, load contents, and additional charges; (4) will not load prohibited materials without written approval; and (5) authorizes charges under Section 6.4.</p>
<p>By typing your full name and checking the box below, you accept and electronically sign this Agreement. <strong>Company:</strong> Texas Dumpster Company LLC.</p>
$agreement_v2$,
  true
where not exists (select 1 from agreement_templates where version = 2);
