-- ============================================================
--  Spanish (Español) translation of Roll Off Dumpster Rental Agreement v2.
--  Customers can switch English <-> Spanish while signing. The English text
--  remains the controlling version (stated at the top of the Spanish text).
--  NOTE: have a fluent speaker / the attorney review before relying on it;
--  edit it any time in Back Office -> Agreement (Español tab).
-- ============================================================

update agreement_templates
set title_es = 'Contrato de Renta de Contenedor Roll Off',
    body_html_es = $agreement_v2_es$
<h3>Contrato de Renta de Contenedor Roll Off</h3>
<p><strong>Texas Dumpster Company LLC</strong></p>
<p><em>Esta es una traducción para su comodidad. Si existe alguna diferencia entre este texto y la versión en inglés, prevalece la versión en inglés.</em></p>
<p><strong>TÉRMINOS IMPORTANTES.</strong> Este Contrato rige la entrega, renta, recolección, transporte y disposición de residuos. El cliente debe revisar los límites de carga, las reglas de materiales prohibidos, los requisitos de acceso, los términos de riesgo a la propiedad y la autorización de cargos adicionales antes de aceptar la entrega.</p>
<p>Contenedor: <strong>roll off de 14 yardas cúbicas</strong>. El plazo de renta, la fecha de entrega, la fecha de recolección, el precio base y el peso incluido son los que aparecen en la confirmación de su pedido.</p>
<p>Formación del contrato. Este Contrato de Renta de Contenedor Roll Off (el &quot;Contrato&quot;) se celebra entre Texas Dumpster Company LLC (la &quot;Compañía&quot;) y la persona o entidad identificada en el pedido (el &quot;Cliente&quot;). La confirmación del pedido, la factura, la página de pago, las fotografías de entrega, el boleto de disposición y cualquier cambio por escrito aprobado por la Compañía forman parte de este Contrato. Si existe un conflicto entre ellos, este Contrato prevalece, a menos que la confirmación del pedido indique expresamente lo contrario.</p>
<h3>1 Servicios de Renta y Plazo</h3>
<p>1.1 La Compañía entregará y recogerá el contenedor identificado en el pedido, sujeto a acceso seguro, disponibilidad de equipo, aceptación por parte de la instalación de disposición, la ley y este Contrato. Las fechas y los horarios son estimados, no garantías, a menos que la Compañía acuerde otra cosa por escrito.</p>
<p>1.2 La renta comienza cuando se entrega el contenedor y termina cuando la Compañía lo recoge. El Cliente debe solicitar la recolección; el fin del período de renta seleccionado no garantiza la recolección automática, a menos que el pedido lo indique expresamente. La posesión continua puede generar la tarifa diaria de extensión indicada en el pedido o en la lista de precios vigente.</p>
<p>1.3 El contenedor sigue siendo propiedad de la Compañía. El Cliente no puede vender, subarrendar, ocultar, alterar, pintar, dañar, fijar objetos a, mover, remolcar, levantar ni permitir que otro transportista dé servicio al contenedor.</p>
<h3>2 Autoridad del Cliente y Condiciones del Sitio</h3>
<p>2.1 El Cliente declara que es dueño del lugar de entrega o que tiene autorización del dueño o del administrador autorizado para ordenar el servicio y aprobar la colocación del contenedor.</p>
<p>2.2 El Cliente elegirá un lugar nivelado, firme y sin obstrucciones que pueda soportar con seguridad el peso combinado del vehículo de entrega, el contenedor y su contenido. El Cliente informará los peligros conocidos, incluidos sistemas sépticos, riego, servicios públicos, suelo blando, adoquines, ramas bajas, portones angostos, pendientes pronunciadas, cables aéreos y accesos restringidos.</p>
<p>2.3 El Cliente autoriza a la Compañía a entrar a la propiedad y a colocar, ajustar o recoger el contenedor usando su criterio razonable. La Compañía puede rechazar o cambiar la colocación cuando el lugar solicitado sea inseguro, ilegal, inaccesible o pueda dañar el equipo o la propiedad.</p>
<p>2.4 Los vehículos y contenedores pesados pueden agrietar, hundir, rayar, manchar o dañar de otra forma entradas de vehículos, pavimento, banquetas, césped, jardinería y mejoras subterráneas, aun cuando se tome un cuidado razonable. El Cliente acepta esos riesgos inherentes de colocación y acceso. Las tablas u otros materiales de protección pueden reducir el riesgo, pero no garantizan su prevención. Esta cláusula no exime de responsabilidad por daños causados por negligencia grave o conducta intencional de la Compañía.</p>
<p>2.5 El Cliente debe obtener cualquier permiso, aprobación de vía pública, autorización de estacionamiento, aprobación de la asociación de vecinos (HOA) u otro consentimiento requerido para la colocación. El Cliente es responsable de las tarifas, multas, costos de remolque y sanciones relacionadas que surjan de su solicitud de colocación o de no obtener la aprobación.</p>
<h3>3 Requisitos de Carga y Uso</h3>
<p>3.1 El Cliente es responsable del contenedor y de todo su contenido desde la entrega hasta la recolección y la aceptación en la disposición, incluido el uso por parte de miembros del hogar, contratistas, invitados, intrusos u otras personas.</p>
<p>3.2 El material debe distribuirse de manera uniforme. Nada puede sobresalir por encima del borde superior ni de los lados, la parte trasera o las puertas. La puerta trasera debe cerrar y asegurarse por completo, y la lona de la Compañía debe poder cubrir la carga sin obstrucciones. El Cliente no debe cargar material después de solicitar la recolección. Si el contenedor está sobrecargado, el Cliente debe descargar o reacomodar el contenido y dejar la carga segura para el transporte legal antes de que la Compañía lo recoja.</p>
<p>3.3 El Cliente no debe exceder el límite de peso legal u operativo del contenedor, las toneladas incluidas indicadas en el pedido ni cualquier límite por material comunicado por la Compañía. Los materiales densos, como tierra, concreto, ladrillo, roca, asfalto, azulejo, yeso, tejas o césped en rollo, requieren aprobación previa por escrito y pueden limitarse a un contenedor parcial o a una carga dedicada.</p>
<p>3.4 A menos que la Compañía apruebe otra cosa por escrito, la carga es solo a mano. El Cliente no puede usar minicargadora, tractor, excavadora, compactadora, vehículo, grúa u otro equipo motorizado para cargar, empujar, golpear o compactar material dentro del contenedor o contra él.</p>
<p>3.5 El Cliente mantendrá a los niños y a las personas no autorizadas lejos del contenedor; mantendrá las puertas aseguradas cuando no se esté cargando; y no se subirá, entrará, quemará material, dormirá ni usará el contenedor para ningún propósito distinto de la carga de residuos aprobada.</p>
<h3>4 Materiales Aceptables y Prohibidos</h3>
<p>4.1 Solo pueden cargarse escombros domésticos, comerciales o de construcción ordinarios que la Compañía y la instalación de disposición designada acepten específicamente. La aceptación varía según la instalación y el tipo de residuo. El Cliente debe consultar a la Compañía antes de cargar cualquier artículo dudoso.</p>
<p>4.2 Lo siguiente está prohibido, a menos que la Compañía dé su aprobación por escrito e identifique el cargo de manejo aplicable:</p>
<ul><li>Residuos peligrosos, tóxicos, radiactivos, explosivos, corrosivos, infecciosos o regulados; asbesto o presunto asbesto; residuos médicos, objetos punzocortantes, fluidos corporales o cadáveres de animales.</li><li>Líquidos, pintura húmeda, solventes, químicos, pesticidas, herbicidas, combustibles, aceites, grasa, cilindros de propano o gas comprimido, baterías y envases a presión.</li><li>Cenizas calientes, material encendido o humeante, fuegos artificiales, municiones, explosivos y materiales capaces de encenderse o reaccionar.</li><li>Refrigeradores, congeladores, aires acondicionados, deshumidificadores u otros equipos con refrigerante, a menos que estén certificados como evacuados y aprobados previamente.</li><li>Llantas, colchones, bases de cama, electrodomésticos, aparatos electrónicos, durmientes de ferrocarril, tocones, tierra, concreto, ladrillo, roca, asfalto, azulejo, yeso, tejas y otros materiales especiales o densos, a menos que estén aprobados previamente de manera específica.</li></ul>
<p>4.3 La pintura de látex puede aceptarse únicamente cuando esté completamente seca o solidificada y cuando lo permita la instalación de disposición. Los envases vacíos deben estar libres de líquidos y residuos en la medida que exija la instalación de disposición.</p>
<p>4.4 Si se encuentra material prohibido, no informado o rechazado, la Compañía puede negarse a recoger el contenedor, retirar y devolver el material, aislar la carga o coordinar su manejo legal. El Cliente pagará todos los cargos resultantes de mano de obra, transporte, limpieza, pruebas, disposición, demoras, reglamentarios y de terceros, más cualquier cargo administrativo legal indicado en la lista de precios. El Cliente sigue siendo responsable de clasificar y desechar legalmente sus residuos.</p>
<h3>5 Acceso para la Recolección y Preparación</h3>
<p>5.1 En la fecha programada de recolección, el Cliente debe proporcionar acceso seguro y sin obstrucciones para el camión y el contenedor. Los vehículos, portones con candado, cables o ramas bajas, animales, nieve, lodo, equipo y otras obstrucciones deben retirarse antes de la llegada.</p>
<p>5.2 La carga debe cumplir con la Sección 3. Si el acceso está bloqueado o el contenedor está sobrecargado, rebosante, inseguro, congelado en su lugar, movido o de otra forma no está listo, la Compañía puede rechazar el servicio. Una recolección bloqueada o fallida está sujeta a una tarifa de viaje fallido de $125. Un contenedor rebosante está sujeto a una tarifa de manejo por sobrellenado de $75, y el Cliente debe descargar o reacomodar el contenido para que la carga sea segura para el transporte legal antes de la recolección. Se debe programar una nueva recolección y pueden aplicarse cargos de renta adicionales.</p>
<p>5.3 La Compañía puede retirar o negarse a transportar cualquier carga insegura. El Cliente es responsable de descargar o corregir la carga por su cuenta. El Cliente no puede entrar al contenedor ni modificarlo mientras la Compañía opera equipo.</p>
<h3>6 Precio, Pago y Cargos Adicionales</h3>
<p>6.1 El Cliente pagará el precio base, los impuestos y las tarifas indicadas en el pedido. A menos que se indique otra cosa, el precio base incluye una entrega, una recolección, un evento de disposición, el período de renta indicado, el área de servicio indicada y el peso incluido.</p>
<p><strong>Lista de Cargos Adicionales</strong></p>
<table style="width:100%;border-collapse:collapse;font-size:.9em;"><thead><tr><th style="text-align:left;border-bottom:1px solid #ccc;padding:4px;">Cargo</th><th style="text-align:left;border-bottom:1px solid #ccc;padding:4px;">Monto</th><th style="text-align:left;border-bottom:1px solid #ccc;padding:4px;">Aplicación</th></tr></thead><tbody>
<tr><td style="padding:4px;border-bottom:1px solid #eee;">Exceso de peso</td><td style="padding:4px;border-bottom:1px solid #eee;">$90 por tonelada</td><td style="padding:4px;border-bottom:1px solid #eee;">Prorrateado según el peso real que exceda el límite incluido. Los materiales pesados o densos están excluidos y requieren aprobación previa y precio por separado.</td></tr>
<tr><td style="padding:4px;border-bottom:1px solid #eee;">Viaje fallido o recolección bloqueada</td><td style="padding:4px;border-bottom:1px solid #eee;">$125</td><td style="padding:4px;border-bottom:1px solid #eee;">Se cobra por cada intento de servicio fallido cuando el acceso para la entrega o recolección está bloqueado o el contenedor no está listo para un servicio seguro.</td></tr>
<tr><td style="padding:4px;border-bottom:1px solid #eee;">Manejo por sobrellenado</td><td style="padding:4px;border-bottom:1px solid #eee;">$75</td><td style="padding:4px;border-bottom:1px solid #eee;">Se cobra cuando el material sobresale del borde superior o impide cubrir o transportar la carga de forma segura. El Cliente debe hacer que la carga sea segura para el transporte antes de la recolección.</td></tr>
</tbody></table>
<p>6.2 Los cargos adicionales también pueden incluir días de renta adicionales; descargas o cambios adicionales; exceso de millaje o recargo por combustible; tiempo de espera; reubicación; cargas excesivas; artículos especiales; manejo de materiales prohibidos; limpieza; daños; multas; permisos; y cargos impuestos por una instalación de disposición. Las tarifas no indicadas arriba son las que se informan en el pedido o en la lista de precios de la Compañía vigente cuando se genera el cargo.</p>
<p>6.3 Los boletos de báscula o los registros de la instalación de disposición determinan el peso real. El clima puede aumentar el peso de los contenidos absorbentes. El Cliente es responsable del exceso de peso causado por lluvia, nieve, hielo, saturación o uso por terceros. El Cliente puede cubrir el contenedor con una cubierta propia solo si se retira antes del servicio y no daña ni obstruye el equipo de la Compañía.</p>
<p>6.4 El Cliente autoriza a la Compañía a cobrar al método de pago registrado los montos adeudados conforme a este Contrato, incluidos los cargos posteriores al servicio respaldados por boletos de báscula, fotografías, facturas, registros de reparación o recibos de terceros. La Compañía proporcionará un recibo o factura detallada. Esta autorización no renuncia a ningún derecho irrenunciable de cuestionar o disputar un cargo incorrecto.</p>
<p>6.5 Los saldos vencidos pueden generar el menor entre 1.5 por ciento mensual o la tasa máxima permitida por la ley. El Cliente reembolsará los costos razonables de cobranza y honorarios de abogados en la medida permitida por la ley.</p>
<h3>7 Cancelaciones, Demoras y Cambios de Servicio</h3>
<p>7.1 Los cargos por cancelación y reprogramación, si los hay, son los informados al pagar o en la confirmación del pedido. Después del despacho o de un intento de entrega, la Compañía puede cobrar una tarifa de viaje o de viaje fallido. Después de la entrega, la renta se considera utilizada aunque el Cliente no coloque material en el contenedor.</p>
<p>7.2 La Compañía no es responsable por demoras o incumplimiento causados por condiciones inseguras, tráfico, clima, cierre de caminos, falla de equipo, cierre o rechazo de la instalación de disposición, acción gubernamental, conflictos laborales, emergencias, fuerza mayor u otras condiciones fuera de su control razonable. La Compañía hará esfuerzos razonables para reprogramar el servicio afectado.</p>
<h3>8 Pérdida, Daños y Limpieza</h3>
<p>8.1 El Cliente es responsable de la pérdida o el daño del contenedor más allá del desgaste normal mientras esté en el lugar de entrega, incluidos robo, vandalismo, grafiti, incendio, movimiento no autorizado, mal uso o daños causados por el Cliente u otras personas. El Cliente informará de inmediato cualquier incidente.</p>
<p>8.2 El Cliente es responsable de limpiar los escombros o fugas causados por su carga, por materiales prohibidos o por el uso del contenedor. La Compañía es responsable de limpiar los escombros causados directamente por su manejo negligente durante la entrega o recolección.</p>
<p>8.3 En la medida permitida por la ley, cada parte defenderá, indemnizará y mantendrá libre de responsabilidad a la otra frente a reclamaciones, pérdidas, multas y costos legales razonables de terceros, en la medida en que hayan sido causados por la negligencia, la conducta intencional o el incumplimiento de este Contrato por parte de esa parte. La obligación del Cliente incluye reclamaciones derivadas de los residuos, de condiciones del sitio no informadas a la Compañía, de las instrucciones de colocación del Cliente y del uso del contenedor por parte del Cliente o de otras personas bajo su control.</p>
<h3>9 Límites de Responsabilidad</h3>
<p>9.1 Excepto por las obligaciones de pago, las obligaciones de indemnización, los daños a la propiedad, las lesiones personales, la negligencia grave, la conducta intencional o la responsabilidad que legalmente no pueda limitarse, ninguna de las partes es responsable ante la otra por daños indirectos, incidentales, especiales, ejemplares, punitivos o consecuentes, incluidas la pérdida de ganancias o de oportunidades.</p>
<p>9.2 Para reclamaciones que legalmente puedan limitarse, la responsabilidad total de la Compañía derivada del pedido no excederá el monto que el Cliente pagó a la Compañía por ese pedido. El Cliente debe dar a la Compañía una oportunidad razonable de inspeccionar y atender cualquier daño reclamado antes de realizar reparaciones, excepto por las medidas de emergencia necesarias para evitar mayores pérdidas.</p>
<h3>10 Incumplimiento y Terminación</h3>
<p>10.1 La Compañía puede suspender el servicio, recoger el contenedor o terminar la renta si el Cliente no paga, viola este Contrato, crea una condición insegura o ilegal, declara falsamente los residuos o interfiere con la propiedad u operaciones de la Compañía. El Cliente sigue siendo responsable de los cargos ya generados y de los costos razonables de recolección y disposición legal.</p>
<p>10.2 Si la Compañía no puede recoger su contenedor, el Cliente otorga a la Compañía y a sus agentes acceso razonable al lugar de entrega para la recolección, sujeto a la ley aplicable. Esto no autoriza alterar el orden público ni entrar ilegalmente.</p>
<h3>11 Términos Legales Generales</h3>
<p>11.1 Este Contrato se rige por las leyes de Texas, sin tener en cuenta sus principios de conflicto de leyes. Cualquier procedimiento judicial debe presentarse ante un tribunal competente en el condado de Williamson, Texas, a menos que la ley aplicable exija otra sede. Antes de presentar una demanda, las partes harán un esfuerzo de buena fe durante al menos 30 días para resolver la disputa mediante aviso por escrito y conversación directa. Cualquiera de las partes puede acudir a un tribunal de reclamos menores cuando sea elegible.</p>
<p>11.2 Los avisos pueden enviarse a la dirección física, correo electrónico o número de teléfono que aparezca en el pedido. Los avisos operativos por mensaje de texto o correo electrónico son efectivos al enviarse; los avisos legales formales son efectivos según lo disponga la ley aplicable.</p>
<p>11.3 Los registros electrónicos, la aceptación mediante casilla, las firmas escritas y las firmas electrónicas pueden usarse para formar y acreditar este Contrato. El Cliente acepta recibir el Contrato, los documentos del pedido, los recibos y las comunicaciones del servicio por medios electrónicos.</p>
<p>11.4 Este Contrato y los documentos del pedido incorporados constituyen el acuerdo completo para el servicio y reemplazan las conversaciones previas sobre ese pedido. Cualquier modificación debe constar por escrito y ser aceptada por ambas partes. El Cliente no puede ceder el Contrato sin el consentimiento por escrito de la Compañía; la Compañía puede cederlo en relación con una transferencia de su negocio o de sus activos.</p>
<p>11.5 Si alguna disposición no es exigible, se aplicará en la máxima medida permitida por la ley y las demás disposiciones continuarán vigentes. La demora o falta de aplicación de una disposición no constituye renuncia. Las disposiciones sobre pago, responsabilidad por los residuos, daños, indemnización, responsabilidad, resolución de disputas y conservación de registros continúan vigentes después de la finalización o terminación.</p>
<h3>12 Reconocimientos del Cliente</h3>
<p>Al firmar o aceptar electrónicamente, el Cliente confirma que: (1) revisó el pedido y este Contrato; (2) entiende el período de renta y el peso incluidos; (3) acepta la responsabilidad por el acceso al sitio, el contenido de la carga y los cargos adicionales; (4) no cargará materiales prohibidos sin aprobación por escrito; y (5) autoriza los cargos conforme a la Sección 6.4.</p>
<p>Al escribir su nombre completo, dibujar su firma y marcar las casillas, usted acepta y firma electrónicamente este Contrato. <strong>Compañía:</strong> Texas Dumpster Company LLC.</p>
$agreement_v2_es$
where version = 2;
